### PR TITLE
fix: fix file permissions (#104)

### LINKED ISSUE #104: Run `chmod a+rx *filename*` on binary after downloading (only on Linux)
Using youtube-dl-exec on platforms like Heroku throws an EACCES error
image
The command `chmod a+rx *name of binary file*` needs to be run on the file to resolve the issue.

Can be achieved by using fs.chmod() in postinstall.js
image

### PR DESCRIPTION
**Pull request by William5553**
Closes #104

### CODE REVIEW

**Comment by Kikobeats** [comment]
why `502`?

If I understand correctly, 493 is actually `755` permission that it should be written as `0o755`

**Comment by William5553** [comment]
It appears to fix this error,
image
but it doesn't make sense since 502 is 766 which doesn't actually have execute permissions. Maybe it should just be changed to 0o777 (511)?

**Comment by Kikobeats** [comment]
What's your environment?

**Comment by Kikobeats** [comment]
Can you deploy your fork that contains the change?

I just setup 0o755 as value

**Comment by William5553** [comment]
The issue appears to be fixed

**Pull request merged**
