### PR TITLE
feat: use node-fetch instead of got

### LINKED ISSUE #35: Use node-fetch over got for postinstall?
node-fetch is smaller, and we don't need these request libraries other than downloading youtube-dl

### PR DESCRIPTION
**Pull request by Kikobeats**
closes #35

### CODE REVIEW

**Comment by Kikobeats** [comment]
Can you review this, @Hazmi35?

**Review by Hazmi35 — APPROVED** [review]
Looks good to me. It works too.

But I don't see `bin-version-check-cli`, and `p-reflect` is used at runtime or postinstall, should I create another issue for that?

**Comment by Kikobeats** [comment]
@Hazmi35 updated; can you review again? 🙂

**Comment by Hazmi35** [comment]
> @Hazmi35 updated; can you review again? 🙂

Looks good, thanks for this change, sorry if I bother you because I didn't make the PR myself because I was late

**Pull request merged**
